-- SEED: Personagens — O Arquivo de Valiran
-- Cole no SQL Editor do Supabase e clique em Run
-- Upsert seguro: insere novos e atualiza existentes pelo ID

INSERT INTO characters (id, name, role, tag, "tagClass", infobox, hero, sections, related, placeholder)
VALUES

-- 1. CASSANDRA BLACKROSE
('cassandra-blackrose','Cassandra Blackrose','Matriarca da Casa Blackrose · bruxa infernal em ascensão','PC',NULL,
'{"rows":[{"k":"Classe","v":"Bruxo · pacto infernal"},{"k":"Origem","v":"Lancaster — distrito nobre decadente"},{"k":"Raça","v":"Humana"},{"k":"Posição","v":"Matriarca da Casa Blackrose"},{"k":"Divindade","v":"Nenhuma — pacto infernal ativo"},{"k":"Status","v":"Ativa — Lancaster","ok":true},{"k":"Pacto","v":"Ativo — favor pendente","danger":true}],"statusNote":"O credor do pacto virá cobrar. Natureza e momento do pagamento desconhecidos. A Casa Blackrose foi reconstruída sobre essa dívida."}'::jsonb,
'Sua mãe morreu pedindo uma promessa que qualquer filha sensata teria recusado. Cassandra prometeu. E quando os meios legítimos falharam, encontrou outros — num baile, num quarto reservado, numa adaga ensanguentada que ficou em suas mãos enquanto o homem que a entregou desaparecia sorrindo.',
'[{"title":"Biografia","paras":["Cassandra cresceu assistindo a Casa Blackrose se desintegrar em torno dela. Sua mãe Elizabeth — a matriarca anterior — havia tentado reerguer a família por meios convencionais e falhado; nos últimos anos, Cassandra foi a única herdeira com disposição para continuar tentando. Frequentou bailes, cultivou contatos, aprendeu a usar beleza e lábia onde títulos não bastavam — e viu os fundos da casa se esgotarem de qualquer forma.","A promessa feita ao leito de morte de Elizabeth — recuperar a nobreza e honrar a Casa — tornou-se o peso que moldou tudo que veio depois. Quando um homem de aura impossível a abordou num baile, Cassandra já sabia o que era. Consultou Khloe; ignorou o aviso. O contrato foi assinado em sangue."]},{"title":"Personalidade","paras":["Cassandra tem a clareza de quem fez escolhas difíceis e se recusa a se desculpar por elas. É calculista, encantadora quando convém, e surpreendentemente franca sobre os limites de sua moralidade. A euforia que sente ao drenar energia vital de outros a perturba genuinamente — não por culpa, mas pela consciência de que pode aprender a gostar muito disso.","Debaixo do pragmatismo há afeto real: por Khloe, pelos criados da casa, pelo nome que carrega. A promessa à mãe não é correntes — é escolha reafirmada todos os dias."]},{"title":"Poderes Adquiridos","paras":["O pacto trouxe poderes progressivos: habilidades sociais amplificadas ao ponto da sobrenatural; chamas infernais que obedece à voz; energia negra que crepita das mãos; afinidade com sombras. O poder mais significativo — e perturbador — é o dreno de energia vital. Cassandra não sabe para onde essa energia vai. Suspeita que não desaparece."]},{"title":"Eventos Notáveis","paras":["Enviou carta convocando aliados e vassalos para reunião na Mansão Blackrose durante o 32º Festival da Alvorada — o evento que marcou o início da Campanha 2. Formalizou aliança com o Clã Sterkhuis via Natan. Khloe Blackrose, sua irmã, morreu em Auberfor num ataque durante os eventos da campanha — foi após essa perda que Katherine Oakwood prometeu ajudá-la a vingar a morte."]}]'::jsonb,
'[{"tag":"Personagem","title":"Khloe Blackrose (irmã)","target":"character:khloe-blackrose"},{"tag":"Personagem","title":"Katherine Oakwood (aliada)","target":"character:katherine-oakwood"},{"tag":"Personagem","title":"Natan Sterkhuis (aliado)","target":"character:natan-sterkhuis"},{"tag":"Facção","title":"Casa Blackrose","target":"factions"},{"tag":"Evento","title":"32º Festival da Alvorada","target":"timeline"}]'::jsonb,
false),

-- 2. KHLOE BLACKROSE
('khloe-blackrose','Khloe Blackrose','Caçadora e Sacerdotisa de Alara · irmã mais velha','PC',NULL,
'{"rows":[{"k":"Classe","v":"Caçadora · Sacerdotisa de Alara"},{"k":"Origem","v":"Lancaster — Mansão Blackrose"},{"k":"Raça","v":"Meia-elfa solar"},{"k":"Pai","v":"Kessio Vedgar · diplomata de Audreosta (desconhecido de seu paradeiro)"},{"k":"Divindade","v":"Alara"},{"k":"Status","v":"MORTA — Auberfor","danger":true}],"statusNote":"Morreu em Auberfor num ataque durante a Campanha 2. Foi após sua morte que Katherine Oakwood prometeu a Cassandra ajudá-la a vingar a irmã."}'::jsonb,
'Khloe tentou ser a âncora da família quando a família estava afundando. Proibiu o pacto. Não conseguiu impedir. Continuou ao lado de Cassandra de qualquer forma — porque é isso que irmãs mais velhas fazem, mesmo quando discordam de tudo.',
'[{"title":"Biografia","paras":["Khloe Blackrose nasceu do caso entre sua mãe Elizabeth e Kessio Vedgar, um diplomata élfico de Audreosta que partiu antes de saber da gravidez. Cresceu como filha ilegítima de casa nobre decadente — habilidosa na caça, onde Elizabeth a treinou desde cedo, mas considerada inapropriada para o jogo político que a mãe queria jogar. Quando Cassandra nasceu, Khloe tornou-se protetora antes mesmo de entender o peso disso.","Após a morte de Elizabeth, assumiu a criação de Cassandra praticamente sozinha, mantendo a casa funcionando enquanto a irmã construía contatos em bailes e festas. Treinou na fé de Alara, tornando-se sacerdotisa; sua conexão com a Floresta das Rosas vinha desse caminho — e foi lá que encontrou Katherine Oakwood pela primeira vez, numa manhã em que as duas começariam a treinar juntas."]},{"title":"Personalidade","paras":["Khloe era direta e de poucas palavras — qualidade que os que a conheciam bem chamavam de honestidade, e os que não a conheciam de frieza. Proibiu terminantemente o pacto infernal de Cassandra. Quando não conseguiu impedir, ficou. Não aprovou; nunca aprovou. Mas a irmã mais nova era sua responsabilidade desde os primeiros anos, e essa responsabilidade não caducava."]},{"title":"Morte","paras":["Khloe morreu em Auberfor num ataque durante a Campanha 2. O evento gerou a aliança entre Cassandra e Katherine Oakwood — que prometeu ajudar a vingar a morte da amiga que criou ao lado desde a infância. Kessio Vedgar, seu pai biológico, nunca soube de sua existência."]}]'::jsonb,
'[{"tag":"Personagem","title":"Cassandra Blackrose (irmã)","target":"character:cassandra-blackrose"},{"tag":"Personagem","title":"Katherine Oakwood (amiga)","target":"character:katherine-oakwood"},{"tag":"Divindade","title":"Alara (deusa)","target":"deity:alara"},{"tag":"Facção","title":"Casa Blackrose","target":"factions"}]'::jsonb,
false),

-- 3. KATHERINE OAKWOOD
('katherine-oakwood','Katherine Oakwood','Druida da Floresta das Rosas · origem desconhecida','PC',NULL,
'{"rows":[{"k":"Classe","v":"Druida"},{"k":"Origem","v":"Floresta das Rosas, Lancaster"},{"k":"Raça","v":"Desconhecida — aparência incomum ao nascer; origem sobrenatural suspeita"},{"k":"Mãe Adotiva","v":"Emerald Oakwood · druida"},{"k":"Companheiro","v":"Ollie · urso"},{"k":"Status","v":"Ativa — aliada da Casa Blackrose","ok":true}],"statusNote":"Prometeu a Cassandra Blackrose ajudá-la a vingar a morte de Khloe. A natureza exata de sua raça e a identidade de seu pai biológico permanecem em aberto."}'::jsonb,
'Ela nasceu com aparência incomum e não fez barulho algum ao vir ao mundo, o que ajudou sua mãe a fingir que havia nascido morta. Um urso gigante a encontrou antes dos druidas. Emerald Oakwood chegou depois e deu-lhe um nome. O resto, ela construiu sozinha.',
'[{"title":"Biografia","paras":["Katherine nasceu de um caso entre uma mulher que vivia com marido abusivo e um homem misterioso conhecido no Porto Dourado. O pai alertou a mãe: o bebê teria aparência incomum e seria tratado como fera. A mãe fingiu que nasceu morta e a deixou na Floresta das Rosas no local combinado. Um grande urso a encontrou antes de qualquer ser humano — e ficou ao lado dela por anos, com comportamento inequivocamente paternal.","Quando um grupo de druidas chegou à floresta e encontrou a criança, Emerald Oakwood foi quem mais se conectou com ela. Deu-lhe o nome Katherine Oakwood e assumiu sua criação. Katherine aprendeu idiomas, aprendeu druidismo, e aprendeu a floresta — o único lar que sempre conheceu."]},{"title":"Ollie","paras":["Durante uma patrulha, Katherine encontrou dois ursos caídos: uma fêmea morta protegendo o filhote ferido. Levou o filhote para o acampamento, cuidou dele, e batizou-o de Ollie. Os dois cresceram juntos, treinaram juntos, desenvolveram estilo de combate único. Ollie a acompanha em todas as missões. O paralelo com o grande urso que cuidou dela não passou despercebido pelos druidas que a criaram."]},{"title":"Aliança com a Casa Blackrose","paras":["A amizade com Khloe Blackrose começou por acaso — as duas se conheceram numa manhã em que Katherine saiu para caminhar com Emerald antes do início de seu treinamento. Khloe estava perdida na floresta procurando um altar de Alara; as três conversaram; Khloe e Katherine começaram o treinamento no dia seguinte, inseparáveis até Khloe partir.","Quando Khloe morreu em Auberfor, Katherine estava lá. Prometeu a Cassandra ajudá-la a vingar a irmã. É esse compromisso que a mantém ao lado da matriarca."]},{"title":"Personalidade","paras":["Katherine tem a tranquilidade de quem cresceu na floresta — não ingênua, mas paciente. Observa antes de agir; reage antes de reclamar. A amizade com Khloe foi uma das poucas relações humanas que construiu com facilidade; a perda pesa de forma que ainda está aprendendo a nomear."]}]'::jsonb,
'[{"tag":"Personagem","title":"Cassandra Blackrose (aliada)","target":"character:cassandra-blackrose"},{"tag":"Personagem","title":"Khloe Blackrose (amiga — morta)","target":"character:khloe-blackrose"},{"tag":"Divindade","title":"Alara (devoção compartilhada)","target":"deity:alara"},{"tag":"Localidade","title":"Floresta das Rosas","target":"map"}]'::jsonb,
false),

-- 4. NATAN STERKHUIS
('natan-sterkhuis','Natan Sterkhuis','Representante do Clã Sterkhuis · ex-guarda em missão diplomática','PC',NULL,
'{"rows":[{"k":"Classe","v":"Guerreiro · ex-guarda de elite"},{"k":"Origem","v":"Highgarde, capital de Oshain"},{"k":"Raça","v":"Humano"},{"k":"Idade","v":"20 anos"},{"k":"Clã","v":"Sterkhuis — construção e decoração nobre"},{"k":"Baixa","v":"8 meses — ainda formalmente soldado"},{"k":"Status","v":"Ativo — Mansão Blackrose, Lancaster","ok":true}]}'::jsonb,
'Aos dezesseis anos foi transferido para guardar a Torre de Highgarde por uma qualidade rara: ele realmente prestava atenção. Aos vinte, chegou a uma mansão em Lancaster, olhou para as pedras do alicerce, e reconheceu a assinatura do próprio clã. Ninguém havia lhe dito que viria parar em casa.',
'[{"title":"Biografia","paras":["Natan cresceu em família ligada à construção civil nobre — o Clã Sterkhuis, fundado há cento e trinta anos, especializado em mansões e ornamentos para famílias nobres. Seu irmão mais velho Hendris era o prodígio dos estudos; Natan era o que nunca conseguia ficar parado. Aos quatorze ingressou na Guarda de Redhall — o mais jovem do posto. Aos dezesseis foi transferido para a Torre de Highgarde por suas habilidades excepcionais de observação.","Quando o pai recebeu o comunicado da Matriarca Blackrose convocando aliados ao Festival da Alvorada, Ernesto optou por enviar Natan em vez de Hendris — argumento direto: Hendris gastaria com segurança; Natan é a segurança. Natan relutou, indicou o irmão, e concordou."]},{"title":"Chegada a Lancaster","paras":["Ao entrar na Floresta das Rosas durante a viagem, percebeu animais que o espreitavam sem atacar — comportamento suficientemente incomum para ser anotado mentalmente. Chegou à Mansão Blackrose, olhou para a fachada, e reconheceu a arquitetura antes de entrar. Confirmou ao encontrar as pedras de alicerce com a assinatura S.K. em cinza das montanhas — exatamente como nos registros do clã. A Mansão Blackrose havia sido construída pelo Clã Sterkhuis gerações atrás como presente à família. Natan chegou, sem ter sido avisado, à casa que os seus construíram."]},{"title":"Personalidade","paras":["Natan é observador antes de ser qualquer outra coisa. Seis anos de serviço ativo na guarda tornaram o instinto militar a primeira linguagem com que lê situações — mas há uma camada de curiosidade genuína abaixo disso que nunca foi totalmente domesticada pelo exército. Está numa missão diplomática com instinto de combatente, e é suficientemente autoconsciente para saber que isso pode ser um problema."]},{"title":"Situação Atual","paras":["Instalado na Mansão Blackrose com baixa de oito meses. Acordo formal com Cassandra assinado; carta enviada ao pai. Está numa cidade estranha, dentro de uma casa que seu clã construiu, ao lado de pessoas que seus avós conheciam — e só ele tem essa perspectiva da situação."]}]'::jsonb,
'[{"tag":"Personagem","title":"Cassandra Blackrose (aliada)","target":"character:cassandra-blackrose"},{"tag":"Personagem","title":"Khloe Blackrose (recebeu na porta)","target":"character:khloe-blackrose"},{"tag":"Facção","title":"Clã Sterkhuis","target":"factions"},{"tag":"Localidade","title":"Highgarde, Oshain","target":"kingdoms"}]'::jsonb,
false),

-- 5. BEATRICE LÖWENHERZ
('beatrice-lowenherz','Beatrice Löwenherz','Veterana da Cruzada do Sol · ex-capitã com marcas de Xathyr','PC',NULL,
'{"rows":[{"k":"Classe","v":"Guerreira veterana · poderes psiônicos (involuntários)"},{"k":"Origem","v":"Lancaster — família da guarda da cidade"},{"k":"Raça","v":"Humana — idade avançada"},{"k":"Ex-cargo","v":"Capitã · 3ª Cruzada do Sol"},{"k":"Divindade","v":"Esmir (histórico) · sem devoção ativa"},{"k":"Status","v":"Ativa — aliada da Casa Blackrose","ok":true},{"k":"Marca","v":"Sussurros de Xathyr ainda presentes","danger":true}],"statusNote":"Perdeu o olho esquerdo por ação de Jammes Howertz — ato que quebrou o controle de Xathyr sobre ela. Jammes pediu que ela o matasse; ela atendeu o pedido."}'::jsonb,
'Ela matou o único homem que amava porque ele pediu. Depois passou doze anos no Grande Escuro tentando matar a criatura que tornou isso necessário. Quando voltou, a cidade que jurou defender não existia mais da mesma forma. Os sussurros de Xathyr, esses, continuaram.',
'[{"title":"Biografia","paras":["A família Löwenherz servia à guarda de Lancaster há gerações; não havia dúvida sobre o caminho de Beatrice. Aos dez anos começou o treinamento sob Jammes Howertz, capitão da guarda e amigo da família — desenvolveu por ele sentimentos que ele provavelmente nunca correspondeu da mesma forma. Jammes a via, supõe-se, como filha.","Em 786 YRD, Xathyr atacou e tomou o controle mental de Lancaster. Beatrice foi uma das afetadas. Descreve a experiência como um grande sonho — sabia o que fazia, mas não parecia ser ela. Jammes golpeou seu olho esquerdo com a espada, o que quebrou o controle. Então pediu que ela acabasse com aquilo. Beatrice o matou. Fugiu para Wolfspine com a parte dela que sobrou."]},{"title":"A 3ª Cruzada e o Grande Escuro","paras":["Alistou-se motivada por vingança — queria destruir Xathyr pessoalmente. Os primeiros meses no Grande Escuro foram horríveis: escuridão total, paranoia, companheiros enlouquecendo. A situação melhorou com as bases nas cidadelas anãs já liberadas pelas cruzadas anteriores. Ascendeu a capitã; seus métodos funcionavam.","Com o tempo, a guerra esfriou e o inimigo passou a operar nas sombras — sua abordagem tornou-se controversa. O ponto de ruptura chegou quando recebeu ordem de localizar e reportar um esconderijo de aberrações. Decidiu atacar diretamente. Um dos seus homens era espião. Perdeu mais da metade do batalhão.","Foi chamada por um superior e dispensada com palavras brandas — enviada de volta como férias. Encarou isso como afronta."]},{"title":"Os Poderes Psiônicos","paras":["O controle de Xathyr deixou marcas além do trauma. Ao estudar as aberrações do Grande Escuro, Beatrice concluiu que o controle havia desbloqueado capacidades psiônicas nela. Odeia esses poderes — os vê como contaminação. Por ironia amarga, foram eles que a salvaram em seu pior momento no subterrâneo."]},{"title":"Retorno e Aliança","paras":["Voltou a Lancaster e encontrou a cidade transformada. Evitava lugares movimentados; via possíveis agentes de Xathyr em cada rosto. Investigou os mortos-vivos que surgiram na Floresta das Rosas após um terremoto misterioso. Procurou a Guilda Internacional de Mercadores como ponto de entrada para as casas nobres; foi apresentada a Cassandra Blackrose e narrou sua história. Tornou-se aliada da Casa."]}]'::jsonb,
'[{"tag":"Personagem","title":"Cassandra Blackrose (aliada)","target":"character:cassandra-blackrose"},{"tag":"Divindade","title":"Xathyr (origem dos traumas)","target":"deity:xathyr"},{"tag":"Facção","title":"Cruzada do Sol","target":"factions"},{"tag":"Localidade","title":"Grande Escuro","target":"planes"},{"tag":"Evento","title":"Controle mental de Xathyr","target":"timeline"}]'::jsonb,
false),

-- 6. REVNA
('revna','Revna','Oráculo dos Corvos · escolhida da Senhora da Rapina','PC',NULL,
'{"rows":[{"k":"Classe","v":"Oráculo"},{"k":"Origem","v":"Tribo do Corvo"},{"k":"Raça","v":"Desconhecida — tribo nômade"},{"k":"Divindade","v":"Senhora da Rapina (Raven Queen)"},{"k":"Olho","v":"Olho esquerdo removido pelos Velstrac","danger":true},{"k":"Caçada","v":"Crucidaemon de Fyria","danger":true},{"k":"Custódia","v":"Galazeth e Lawrence — após julgamento","danger":true},{"k":"Status","v":"Ativa — base em Silverhain","ok":true}],"statusNote":"Marcada com símbolos Velstrac — dor contínua; os Velstrac sabem sempre onde ela está. Sob custódia do grupo após julgamento pelas escolhas que fez com os Velstrac."}'::jsonb,
'Ela sempre viu as catástrofes antes que acontecessem. O problema era que nunca entendia seu papel nelas — até perceber espíritos sendo devorados por algo que não deveria existir. Esse chamado foi o único que não precisou de interpretação.',
'[{"title":"Biografia","paras":["Revna foi destinada desde o nascimento a ser a Oráculo dos Corvos da sua tribo — uma função que existe numa linha tênue entre dom e fardo. Passou pelo ritual de conexão com a Senhora da Rapina, trocando um pedaço da alma por um pedaço do poder divino da deusa: visões, percepções, uma ligação direta com o ciclo da morte que a maioria das pessoas nunca experimenta nem de longe.","O problema sempre foi a interpretação. Revna via catástrofes com clareza; via seu papel nelas como névoa. Quando começou a perceber espíritos sendo capturados por uma entidade que não deveria existir — Ayael, preso no Plano de Energia Negativa, perturbando o ciclo da morte — esse foi o único chamado que não precisou de tradução. Partiu para Wolfspine. O pai não aprovou."]},{"title":"Marcas e Traumas","paras":["Em negociação com os Velstrac para obter informações sobre a corrupção, Revna pagou com o olho esquerdo — removido como parte do preço. Os Velstrac também a marcaram com símbolos permanentes: dor contínua, e a certeza de que saberão sempre onde ela está. A Crucidaemon de Fyria desenvolveu ligação mágica de caça com ela após a batalha em que Feronar morreu.","O grupo a julgou pelas escolhas com os Velstrac — o que obteve veio a um preço que outros carregam junto com ela. Ficou sob custódia de Galazeth e Lawrence como resultado."]},{"title":"O Que Descobriu","paras":["As informações obtidas dos Velstrac moldaram a compreensão do grupo sobre a crise: a corrupção vem do sofrimento de Ayael, anjo filho de Lamidriel preso no Plano de Energia Negativa. O rasgo planar foi aberto por Noel Braent. Alguém manipula ativamente essa energia — a mesma entidade que, Revna acredita, manipulava a corrupção na Floresta das Rosas."]},{"title":"Ações Notáveis","paras":["Curou Lady Joice Rosewood da infecção da Princesa Pálida. Curou Dykorkis durante o combate com Cevras na Torre de Fallburgo. Contatou o Império de Ferro para negociar troca de informações pelo resgate de Diego. Prometeu visitar Grin na prisão de Silverhain — promessa ainda pendente."]}]'::jsonb,
'[{"tag":"Divindade","title":"Senhora da Rapina (deusa)","target":"deity:senhora-da-rapina"},{"tag":"Divindade","title":"Ayael (causa da crise)","target":"deity:ayael"},{"tag":"Divindade","title":"Fyria (Crucidaemon a caça)","target":"deity:fyria"},{"tag":"Personagem","title":"Isla (emissária morta)","target":"character:isla"},{"tag":"Lore","title":"A Fenda Planar de Ayael","target":"planes"}]'::jsonb,
false),

-- 7. DIEGO VANS LOUPD'OR
('diego-vans-loupd-or','Diego Vans Loupd''or','Paladino de Lamidriel · capturado nas catacumbas de Lindhaven','PC',NULL,
'{"rows":[{"k":"Classe","v":"Paladino de Lamidriel / Bahamut"},{"k":"Origem","v":"Wolfspine — família comum"},{"k":"Raça","v":"Humano"},{"k":"Mentor","v":"Thale Vans Loupd''or — paradeiro desconhecido"},{"k":"Divindade","v":"Lamidriel / Bahamut"},{"k":"Status","v":"CAPTURADO — localização desconhecida","danger":true}],"statusNote":"Capturado pela Princesa Pálida de Lindhaven ao se render voluntariamente para salvar o grupo. Lawrence carrega sua espada como símbolo da promessa de resgate."}'::jsonb,
'Ele entregou a espada porque a Princesa Pálida disse que, se o fizesse, todos os outros sairiam. Diego acreditou que era verdade. Talvez fosse. Lawrence ficou com a espada e prometeu voltar.',
'[{"title":"Biografia","paras":["Diego cresceu em Wolfspine com inclinação natural para a justiça — não como conceito abstrato, mas como impulso visceral diante de injustiças concretas. Suas habilidades físicas nunca foram seu ponto forte; sua presença, sim. Thale Vans Loupd''or o notou e o levou sob tutela para a República Prateada, onde Diego foi treinado no templo de Lamidriel. Retornou a Wolfspine aos vinte e um anos como paladino formado.","Sua motivação central, que articulou em palavras numa das sessões que moldaram o grupo: transformar rostos frios em sorrisos e tempos escuros em luz. Diego acredita nela completamente."]},{"title":"O Sacrifício de Lindhaven","paras":["Nas catacumbas de Lindhaven, a Princesa Pálida apresentou ao grupo uma escolha: Diego se rendia e todos os outros saíam. Diego não hesitou. Trocou um aperto de mão final com Lawrence, entregou a espada. A Princesa Pálida o levou. Lawrence ficou com a espada de Diego — um objeto que passou a ser símbolo físico de uma promessa que organiza a missão atual."]},{"title":"Conexões","paras":["Thale Vans Loupd''or foi seu mentor e figura paterna — seu paradeiro é desconhecido. Lawrence é seu melhor amigo; o sacrifício de Diego em Lindhaven é o evento central que move Lawrence no presente. Lamidriel é seu deus — o mesmo cujo filho Ayael é a fonte da corrupção que Diego combatia."]}]'::jsonb,
'[{"tag":"Personagem","title":"Lawrence Cainhurst (melhor amigo)","target":"character:lawrence-cainhurst"},{"tag":"Personagem","title":"Thale Vans Loupd''or (mentor)","target":"character:thale-vans-loupd-or"},{"tag":"Divindade","title":"Lamidriel (deusa)","target":"deity:lamidriel"},{"tag":"Evento","title":"Queda de Lindhaven","target":"timeline"}]'::jsonb,
false),

-- 8. LAWRENCE CAINHURST
('lawrence-cainhurst','Lawrence Cainhurst','Paladino de Lamidriel · carrega a mácula e a espada de Diego','PC',NULL,
'{"rows":[{"k":"Classe","v":"Paladino de Lamidriel (recentemente ascendido)"},{"k":"Origem","v":"Floresta das Rosas"},{"k":"Raça","v":"Humano"},{"k":"Mentor","v":"Jorah Londor — paradeiro desconhecido"},{"k":"Divindade","v":"Lamidriel (ascensão confirmada — origem do poder incerta)"},{"k":"Mácula","v":"Energia de Ayael — irremovível","danger":true},{"k":"Afinidade","v":"Energia negativa — energia positiva tem efeitos contrários"},{"k":"Status","v":"Ativo — missão em Nova Lancaster","ok":true}],"statusNote":"Afetado por Xathyr no passado; memórias desse período são fragmentadas. Questiona se a ascensão a paladino veio de Lamidriel ou da mácula que carrega."}'::jsonb,
'Nasceu com afinidade para energia negativa — uma criança que a energia positiva quase matava. Sobreviveu à queda de Lancaster porque a corrupção não o afetava da mesma forma que afetava os outros. Agora carrega a mácula de Ayael dentro de si e às vezes se pergunta se o poder que recebeu de Lamidriel é mesmo de Lamidriel.',
'[{"title":"Biografia e a Maldição","paras":["Lawrence nasceu diferente. Boatos de criança amaldiçoada se espalharam — um capelão forçou um ritual de remoção com energia positiva que quase o matou. Jorah Londor interrompeu o ritual e o devolveu à mãe. A verdade sobre a natureza de Lawrence nunca foi maldição: era afinidade com energia negativa — o oposto do esperado de uma criança numa comunidade devota de Lamidriel.","Jorah tornou-se figura paterna, ensinando o caminho do cavaleiro e a fé de Lamidriel. A mãe ensinou ocultismo e esoterismo. Lawrence cresceu entre essas duas linguagens — e foi à guarda de Lancaster como Cavaleiro de Lamidriel, um dos poucos que cultuavam o Titã abertamente."]},{"title":"A Influência de Xathyr e a Queda de Lancaster","paras":["Durante um período que ele lembra mal, Lawrence foi afetado pela influência de Xathyr. Suas memórias desse tempo são fragmentadas — recuperou alguma clareza depois da libertação de Lancaster por Vaglies. A afinidade com energia negativa o protegeu durante a queda de Lancaster de formas que outros sobreviventes não tiveram."]},{"title":"A Mácula","paras":["Ferido por uma Shadow nas catacumbas de Lindhaven, Lawrence carrega a mácula de Ayael — energia nécrotica impressa no corpo. Revna e sacerdotes de Silverhain tentaram remover sem sucesso completo. A mácula permanece. Lawrence teme estar trilhando o mesmo caminho que Ayael — um ser de luz corrompido em sofrimento eterno."]},{"title":"A Ascensão a Paladino","paras":["Era apenas Cavaleiro até após a queda de Lindhaven. Consumido por culpa — Diego se sacrificara por ele; herdara a liderança de um povo deslocado — clamou por Lamidriel diante de um altar improvisado pelos refugiados. Foi atendido.","A dúvida central persiste: é mesmo Lamidriel quem concede esse poder? A mácula de Ayael e a afinidade com energia negativa tornam a origem do poder genuinamente ambígua."]},{"title":"Missão Atual","paras":["Infiltrado em Nova Lancaster com John. Objetivo imediato: encontrar guia para o Grande Escuro via contatos de Vrakmash. Objetivo maior: localizar e reativar a Cruzada do Sol. Objetivo pessoal: resgatar Diego. Carrega a espada de Diego como símbolo físico dessa promessa."]}]'::jsonb,
'[{"tag":"Personagem","title":"Diego Vans Loupd''or (capturado)","target":"character:diego-vans-loupd-or"},{"tag":"Personagem","title":"Jorah Londor (mentor — desaparecido)","target":"character:jorah-londor"},{"tag":"Divindade","title":"Lamidriel (deusa)","target":"deity:lamidriel"},{"tag":"Divindade","title":"Ayael (mácula)","target":"deity:ayael"},{"tag":"Divindade","title":"Xathyr (influência passada)","target":"deity:xathyr"},{"tag":"Facção","title":"Cruzada do Sol","target":"factions"},{"tag":"Localidade","title":"Nova Lancaster","target":"kingdoms"}]'::jsonb,
false),

-- 9. GALAZETH
('galazeth','Galazeth','Diplomata Kobold da República Prateada · aspirante a reformador','PC',NULL,
'{"rows":[{"k":"Classe","v":"Diplomata · habilidades arcanas"},{"k":"Origem","v":"Campos de Salmão, República Prateada de Bahamut (província Azul)"},{"k":"Raça","v":"Kobold"},{"k":"Divindade","v":"Bahamut (institucional)"},{"k":"Linhagem","v":"Clama ter sangue do dragão ancião azul desaparecido da República"},{"k":"Status","v":"Ativo — base em Silverhain","ok":true}]}'::jsonb,
'Galazeth está cercado de draconatos e dragões que o olham de cima — literal e figurativamente. Sua ambição não é derrotá-los nesse jogo. É mudar as regras do jogo para que Kobolds não precisem mais começar do último lugar.',
'[{"title":"Biografia","paras":["Galazeth cresceu nos Campos de Salmão, na província dos Kobolds Azuis da República Prateada de Bahamut — um lugar onde a hierarquia dracônica torna o cotidiano dos Kobolds uma lição constante sobre onde eles ficam na ordem das coisas. Enfrenta preconceito constante: Kobolds abaixo de draconatos, draconatos abaixo de dragões, a estrutura firmemente mantida e raramente questionada.","Galazeth questiona. Atendeu ao chamado da Cruzada Prateada como representante diplomático — não como escolha óbvia, mas como posição que conquistou. Clama ter sangue do dragão ancião azul desaparecido da República, o que seus detratores consideram aspiração e seus aliados consideram possibilidade."]},{"title":"Personalidade","paras":["Galazeth é arguto, articulado, e menos deferente do que os que o cercam gostariam. Ficou do lado de Revna durante o julgamento pelos Velstrac — uma escolha que revelou sua capacidade de ir contra o peso do grupo. Levantou o ponto sobre a República estar enfraquecida pelo autoexílio da anciã negra, o que ofendeu Dykorkis; não se desculpou."]},{"title":"Ações Notáveis","paras":["Usou Counterspell contra magia de Divination desconhecida durante viagem — ação rápida que indicou profundidade arcana além do esperado de um diplomata. Ajudou a decifrar o livro codificado da Blackflame."]}]'::jsonb,
'[{"tag":"Facção","title":"República Prateada de Bahamut","target":"factions"},{"tag":"Divindade","title":"Bahamut (divindade)","target":"deity:bahamut"},{"tag":"Personagem","title":"Dykorkis (tensão)","target":"character:dykorkis"}]'::jsonb,
false),

-- 10. JOHN
('john','John','Operativo furtivo · em missão com Lawrence em Nova Lancaster','PC',NULL,
'{"rows":[{"k":"Classe","v":"Desconhecida — furtividade e destreza confirmadas"},{"k":"Origem","v":"Desconhecida"},{"k":"Raça","v":"Desconhecida"},{"k":"Status","v":"Ativo — missão em Nova Lancaster com Lawrence","ok":true}],"statusNote":"História e origem a serem adicionadas futuramente. Placeholder ativo."}'::jsonb,
'Abriu um livro lacrado com armadilha sem ativá-la. Evacuou uma nobre sob cerco sem ser visto. Não faz barulho, não faz perguntas desnecessárias. O que faz antes disso tudo, ninguém ainda sabe ao certo.',
'[{"title":"O que se sabe","paras":["John é operativo de campo. Seu histórico antes de se juntar ao grupo ainda não foi documentado — o que se conhece dele é o que ele faz: abriu o livro lacrado da Blackflame sem acionar a armadilha; evacuou Lady Joice Rosewood durante o cerco de Lindhaven sem ser detectado; acompanha Lawrence na infiltração de Nova Lancaster."]},{"title":"Missão Atual","paras":["Em Nova Lancaster ao lado de Lawrence. Objetivo conjunto: encontrar guia para o Grande Escuro, localizar contatos de Vrakmash, e eventualmente resgatar Diego. O silêncio de John sobre seu próprio passado é, até agora, informação em aberto."]}]'::jsonb,
'[{"tag":"Personagem","title":"Lawrence Cainhurst (parceiro de missão)","target":"character:lawrence-cainhurst"},{"tag":"Localidade","title":"Nova Lancaster","target":"kingdoms"}]'::jsonb,
true),

-- 11. RAGAE EGER
('ragae-eger','Ragae Eger','Patrulheiro · nascido do ovo de Dragão de Prata','PC',NULL,
'{"rows":[{"k":"Classe","v":"Patrulheiro"},{"k":"Origem","v":"Floresta · criado por Dragão de Cobre"},{"k":"Raça","v":"Nascido de ovo de Dragão de Prata"},{"k":"Mentor","v":"Dragão de Cobre — paradeiro desconhecido"},{"k":"Status","v":"MORTO — alma consumida pela Crucidaemon","danger":true}],"statusNote":"Sua alma foi consumida — não seguiu o ciclo natural da morte. Feronar se sacrificou para conter a Crucidaemon no mesmo evento."}'::jsonb,
'Um Dragão de Cobre o criou na floresta e ensinou o caminho do Patrulheiro. Quando a Floresta de Lancaster foi destruída, Ragae disse que foi como um tiro no peito. Foi a Wolfspine buscar ajuda. A Crucidaemon encontrou-o antes que pudesse dar o próximo passo.',
'[{"title":"Biografia","paras":["Ragae nasceu de um ovo de Dragão de Prata — o que isso significa exatamente sobre sua natureza ainda não foi completamente compreendido. Quem o criou foi um Dragão de Cobre, que lhe ensinou a viver da floresta e a retribuir em dobro o que dela recebia. Sob orientação do Dragão de Cobre, tornou-se Patrulheiro — alguém que conhece o terreno como extensão de si mesmo.","Quando a destruição chegou à Floresta de Lancaster, Ragae descreveu o que sentiu como um tiro no peito. Partiu para Wolfspine buscar ajuda. Não chegou a dar o próximo passo."]},{"title":"Morte","paras":["Ragae foi morto pela Crucidaemon de Fyria durante a batalha ao lado de Feronar. A Crucidaemon consumiu sua alma — um ato que viola o ciclo natural da morte e que impede qualquer forma de descanso ou julgamento. Feronar se sacrificou para conter a criatura no mesmo evento e morreu no processo. A questão de se a alma de Ragae pode ser recuperada permanece sem resposta."]}]'::jsonb,
'[{"tag":"Divindade","title":"Fyria (Crucidaemon)","target":"deity:fyria"},{"tag":"Divindade","title":"Senhora da Rapina (ciclo violado)","target":"deity:senhora-da-rapina"},{"tag":"Personagem","title":"Feronar (morreu para conter a criatura)","target":"character:feronar"}]'::jsonb,
false),

-- 12. FAELYNN ELINTHOR
('faelynn-elinthor','Faelynn Elinthor','Guerreira Divina de Esmir · Tiefling com herança infernal e voz interior','PC',NULL,
'{"rows":[{"k":"Classe","v":"Guerreira Divina de Esmir · Feiticeira"},{"k":"Origem","v":"Audreosta, Família Elinthor"},{"k":"Raça","v":"Tiefling (meio-elfo imperial — herança infernal antiga)"},{"k":"Pai","v":"Elfo imperial"},{"k":"Mãe","v":"Humana barda"},{"k":"Divindade","v":"Esmir"},{"k":"Companheiro","v":"Amon — Displacer Beast"},{"k":"Status","v":"Ativa","ok":true}],"statusNote":"Carrega voz interior que a instiga a ações prejudiciais. Encontrou e destruiu um colar com pedra negra de aura sombria — manteve o objeto consigo. Ral''zarek, seu mentor infernal, serve a um deus diferente."}'::jsonb,
'Nasceu Tiefling numa cidade de elfos solares que chamam de maldição o que não conseguem explicar. Aprendeu a fé de Esmir com o pai e o irmão; aprendeu a usar o poder infernal com Ral''zarek; aprendeu que a voz na cabeça não vai embora — mas pode ser ignorada, por ora.',
'[{"title":"Biografia","paras":["Faelynn nasceu Tiefling de pai elfo imperial e mãe humana barda — a herança infernal antiga da linhagem do pai se manifestou nela de forma que os elfos solares de Audreosta interpretaram como sinal de maldade. Foi isolada da comunidade por isso; seu meio-irmão Lithrandil e seu pai a ensinaram a fé de Esmir como âncora. A mãe ensinou rituais arcanos e que sua herança tinha poder — não maldição, mas instrumento.","Conheceu Ral''zarek, um Tiefling amigo da mãe, que a ensinou a usar o poder infernal de forma prática. Ral''zarek deixou-lhe Amon — um Displacer Beast que se tornaria companheiro de combate — e partiu, deixando apenas a menção de que serve a um deus diferente.","O que isso significa permanece em aberto."]},{"title":"Amon","paras":["Faelynn e Amon desenvolveram estilo de combate único ao longo do tempo — não o uso tradicional de besta de carga, mas parceria de coordenação real. Amon é presente e ligação com Ral''zarek; Faelynn não separaria as duas coisas mesmo que pudesse."]},{"title":"A Voz Interior","paras":["Faelynn carrega uma voz que a instiga a fazer coisas ruins. Não é controle — é pressão constante. Aprendeu a distinguir quando está ouvindo a voz e quando está pensando por conta própria, mas a distinção nem sempre é fácil em momentos de estresse."]},{"title":"O Trio Independente","paras":["Faelynn, Kyanna e Lithrandil investigaram uma corrupção que a Igreja de Esmir ignorou. Diante do descaso institucional, os três juraram agir de forma independente — sem aguardar aprovação de estruturas que não priorizam o que precisam ser priorizados."]}]'::jsonb,
'[{"tag":"Divindade","title":"Esmir (divindade)","target":"deity:esmir"},{"tag":"Personagem","title":"Kyanna Elshar (melhor amiga)","target":"character:kyanna-elshar"},{"tag":"Personagem","title":"Lithrandil (meio-irmão)","target":"character:lithrandil"}]'::jsonb,
false),

-- 13. KYANNA ELSHAR
('kyanna-elshar','Kyanna Elshar','Clériga de Esmir · anã das cinzas resgatada do Grande Escuro','PC',NULL,
'{"rows":[{"k":"Classe","v":"Clériga de Esmir · especializada em cura"},{"k":"Origem","v":"Grande Escuro — nascida lá como escrava"},{"k":"Raça","v":"Anã das Cinzas"},{"k":"Nome Anterior","v":"98657 (número de escrava)"},{"k":"Adotada por","v":"Família devota de Esmir"},{"k":"Divindade","v":"Esmir"},{"k":"Status","v":"Ativa","ok":true}],"statusNote":"Homem que a resgatou tinha símbolo de sol — possivelmente da Cruzada do Sol. Identidade desconhecida. Aragrett, anã das cinzas desaparecida no Grande Escuro, pode ter conexão com sua origem."}'::jsonb,
'Até os doze anos ela não tinha nome — apenas o número 98657 marcado no braço. Um homem com símbolo de sol na armadura a resgatou e levou para a superfície. Nunca descobriu quem era. Tornou-se clériga de Esmir. Às vezes, curar os outros é a única forma de fazer sentido de ter sido salva.',
'[{"title":"Biografia","paras":["Kyanna nasceu no Grande Escuro numa comunidade de anões das cinzas mantidos como escravos — separada da mãe semanas após o nascimento, sem nome, apenas um número marcado no braço. Aos doze anos, um homem com símbolo de sol na armadura a resgatou e a levou para a superfície. Ela nunca descobriu quem era; a família que a adotou era devota de Esmir, e foi nessa fé que encontrou estrutura o suficiente para construir uma identidade.","Batizada como Kyanna Elshar, formou-se clériga com especialidade em cura. Sofreu preconceito dentro do próprio clero por ser anã das cinzas — a hierarquia da Igreja nem sempre pratica o que prega sobre o sacrifício e o acolhimento. Conheceu Faelynn Elinthor na mesma instituição; tornaram-se inseparáveis.","Sofreu preconceito dentro do próprio clero por ser anã das cinzas."]},{"title":"O Grande Escuro","paras":["Kyanna nasceu no Grande Escuro e conhece o lugar de dentro — não como aventureira, mas como alguém que cresceu nele antes de saber que havia outra coisa. Essa perspectiva é tanto ferida quanto recurso. A menção de Aragrett — anã das cinzas desaparecida no Grande Escuro — pode ter ressonância com sua própria origem que ainda não foi explorada."]},{"title":"O Trio Independente","paras":["Junto com Faelynn e Lithrandil, investigou uma corrupção ignorada pela Igreja e jurou agir independentemente do aparato institucional. É a âncora de cura do grupo — e frequentemente a perspectiva mais sóbria quando as coisas escalam."]}]'::jsonb,
'[{"tag":"Divindade","title":"Esmir (divindade)","target":"deity:esmir"},{"tag":"Personagem","title":"Faelynn Elinthor (melhor amiga)","target":"character:faelynn-elinthor"},{"tag":"Personagem","title":"Lithrandil (companheiro)","target":"character:lithrandil"},{"tag":"Facção","title":"Cruzada do Sol (possível ligação via resgate)","target":"factions"},{"tag":"Localidade","title":"Grande Escuro","target":"planes"}]'::jsonb,
false),

-- 14. HARABELLA THUNDERVOICE
('harabella-thundervoice','Harabella Thundervoice','Líder Shifter · devota de Melora · morta em Fallburgo','PC',NULL,
'{"rows":[{"k":"Classe","v":"Líder — combatente"},{"k":"Origem","v":"Floresta das Rosas"},{"k":"Raça","v":"Shifter"},{"k":"Divindade","v":"Melora (bênção do batismo — três espíritos da tempestade)"},{"k":"Status","v":"MORTA — Torre de Fallburgo","danger":true}],"statusNote":"Corpo levado pelos Homens do Pantano após a morte. Encontrado como morto-vivo na Torre de Fallburgo pelos companheiros."}'::jsonb,
'Melora a abençoou ao nascer com três espíritos da tempestade. Harabella levou seu povo para fora da floresta corrompida, foi buscar ajuda em Wolfspine, e morreu na Torre de Fallburgo defendendo o que havia ido buscar.',
'[{"title":"Biografia","paras":["Harabella era líder de seu povo, uma comunidade Shifter que vivia na Floresta das Rosas antes que a corrupção tornasse a floresta inabitável. Recebeu a bênção de Melora ao nascer — três espíritos da tempestade selados em seu batismo, uma raridade que indicava favor divino ativo. Liderou seu povo para fora da floresta quando a situação se tornou insustentável; foi a Wolfspine buscar ajuda.","Foi em Wolfspine que conheceu Wander Bristoll. Os dois voltaram juntos ao grupo. Morreram juntos na Torre de Fallburgo. Os corpos foram levados pelos Homens do Pantano — e depois encontrados pelo grupo como mortos-vivos dentro da mesma Torre."]}]'::jsonb,
'[{"tag":"Personagem","title":"Wander Bristoll (morreu junto)","target":"character:wander-bristoll"},{"tag":"Divindade","title":"Melora (deusa)","target":"deity:melora"},{"tag":"Localidade","title":"Floresta das Rosas","target":"map"}]'::jsonb,
false),

-- 15. WANDER BRISTOLL
('wander-bristoll','Wander Bristoll','Fundador da Sília Arms · veterano de Lancaster · morto em Fallburgo','PC',NULL,
'{"rows":[{"k":"Classe","v":"Guerreiro veterano"},{"k":"Nome Real","v":"Sonar Bristoll"},{"k":"Origem","v":"Lancaster"},{"k":"Raça","v":"Humano"},{"k":"Companhia","v":"Sília Arms (fundada por ele)"},{"k":"Status","v":"MORTO — Torre de Fallburgo","danger":true}],"statusNote":"Corpo levado pelos Homens do Pantano. Encontrado como morto-vivo na Torre de Fallburgo. Membros da Sília Arms: Ethan Duskkar (The Blade Breaker), Vyck Waygmar (The Festival Vyck), Junnye Farlan (Jukill), Lascor Farlan (The Drill)."}'::jsonb,
'Sua última promessa à esposa morta era uma última jornada antes de reencontrá-la. Conheceu Harabella, voltou à ativa, morreu em Fallburgo. A promessa, ao menos, foi cumprida.',
'[{"title":"Biografia","paras":["Sonar Bristoll foi prodígio militar de Lancaster — talento precoce que lhe rendeu reputação antes dos vinte anos. Casou com Sília; ela morreu por um Wyvern. Fundou a companhia mercenária Sília Arms em memória dela. Retirou-se após dezessete anos — a última promessa à esposa era uma jornada final antes de reencontrá-la.","Conheceu Harabella em Wolfspine quando ela foi buscar ajuda para seu povo. Voltou à ativa. Morreu na Torre de Fallburgo ao lado dela. Os corpos foram levados pelos Homens do Pantano e encontrados pelo grupo como mortos-vivos dentro da mesma Torre — uma brutalidade que o grupo não esqueceu."]}]'::jsonb,
'[{"tag":"Personagem","title":"Harabella Thundervoice (morreu junto)","target":"character:harabella-thundervoice"},{"tag":"Facção","title":"Sília Arms","target":"factions"}]'::jsonb,
false),

-- 16. ISLA
('isla','Isla','Emissária da Senhora da Rapina · morta pela Princesa Pálida da Torre','PC',NULL,
'{"rows":[{"k":"Classe","v":"Serva da Senhora da Rapina"},{"k":"Origem","v":"Desconhecida"},{"k":"Divindade","v":"Senhora da Rapina (vínculo direto)"},{"k":"Status","v":"MORTA — Torre de Fallburgo","danger":true}],"statusNote":"Morta pela Princesa Pálida da Torre de Fallburgo."}'::jsonb,
'A Senhora da Rapina lhe enviou visões de que uma escolhida estava em perigo. Isla foi a Wolfspine encontrá-la, lutou ao lado dela, e morreu antes que pudesse saber se o perigo foi evitado.',
'[{"title":"Missão","paras":["Isla recebeu visões da Senhora da Rapina indicando que Revna — a Oráculo dos Corvos — estava em perigo. Foi enviada ao mundo material para encontrá-la e protegê-la. Chegou a Wolfspine, identificou Revna, juntou-se ao grupo. Lutou ao lado deles. Morreu na Torre de Fallburgo pela Princesa Pálida.","Sua missão foi interrompida — não completada. O perigo que devia proteger Revna ainda existe."]}]'::jsonb,
'[{"tag":"Personagem","title":"Revna (a quem protegia)","target":"character:revna"},{"tag":"Divindade","title":"Senhora da Rapina (enviou Isla)","target":"deity:senhora-da-rapina"}]'::jsonb,
false),

-- 17. RIAN BHEINI
('rian-bheini','Rian Bheini','Patrulheiro de Wolfspine · morte foi o gatilho inicial','PC',NULL,
'{"rows":[{"k":"Classe","v":"Patrulheiro"},{"k":"Origem","v":"Wolfspine"},{"k":"Status","v":"MORTO — antes do início da Campanha 3","danger":true}]}'::jsonb,
'Rian Bheini morreu antes da história começar. Sua morte foi o gatilho que colocou todo o resto em movimento.',
'[{"title":"Papel","paras":["Patrulheiro de Wolfspine, Rian Bheini morreu antes do início da Campanha 3. Sua morte foi o evento que desencadeou os acontecimentos iniciais — o gatilho que trouxe os heróis juntos. Os detalhes completos de suas circunstâncias permanecem como registro parcial."]}]'::jsonb,
'[]'::jsonb,
true)

ON CONFLICT (id) DO UPDATE SET
  name       = EXCLUDED.name,
  role       = EXCLUDED.role,
  tag        = EXCLUDED.tag,
  "tagClass" = EXCLUDED."tagClass",
  infobox    = EXCLUDED.infobox,
  hero       = EXCLUDED.hero,
  sections   = EXCLUDED.sections,
  related    = EXCLUDED.related,
  placeholder = EXCLUDED.placeholder;
